<?php
/**
  *Implements hook_permisstion().
*/
function cronmonitor_permission() {
  return array(
    'administer cronmonitor' => array(
      'title' => t('Administer Cronmonitor'),
      'description' => t('Perform administration tasks for Cronmonitor.'),
    ),
  );
}
/**
  *Implements hook_menu().
*/
 function cronmonitor_menu() {
    $items['admin/config/cronmonitor'] = array(
      'title'            => 'Cron Monitor Setting',
      'type'             => MENU_NORMAL_ITEM,
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('cronmonitor_admin_form'),
      'access arguments' => array('administer cronmonitor'),
    );
    return $items;
  }
/**
  *Administer form for Cron Monitor.
*/

function cronmonitor_admin_form($form, &$form_state)
{
	$form['cronmonitor_enable'] = array(
	'#type'          =>'checkbox', 
	'#title'         => t('Enable Cron Monitor.'),
        '#default_value' => variable_get('cronmonitor_enable',0),

);

	$form['cronmonitor_email_text'] = array(
	'#title'          => t('Text to send'),
	'#type'           => 'textarea',
	'#default_value'  => variable_get('cronmonitor_email_text',''),
);


	return system_settings_form($form);
}

/**
  *Implements hook_cron().
*/
function cronmonitor_cron()
{
	
		 // send cromonitor email
	 drupal_mail('cronmonitor', 'cronmonitor_email', 'tuan.nh@sutrixsolutions.com', language_default());
}


/**
  *Implements hook_mail().
*/

function cronmonitor_mail($key,&$message)
{
	switch($key)
	{
		case 'cronmonitor_email' :
		  $message['subject']  = t('Cron Monitor Report');
		  $message['body'][]   = t('This is body mail on @site-name'); 
		  $message['body'][]   = t(variable_get('cronmonitor_email_text',''));
		  break;				
	}
}


